name: TAKI 720p30 LOW
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Stream
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y xvfb ffmpeg chromium-browser
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x720x16 &
          sleep 3
          
          chromium-browser --no-sandbox --disable-dev-shm-usage \
            --disable-gpu --single-process --no-zygote --mute-audio \
            --window-size=1280,720 --kiosk ${{ vars.OVERLAY_URL }} &
          sleep 15
          
          # 720p 30fps فقط + 1 thread + بلا صوت
          ffmpeg -f x11grab -video_size 1280x720 -framerate 30 -i :99 \
            -c:v libx264 -preset ultrafast -tune zerolatency \
            -b:v 2500k -maxrate 2500k -bufsize 5000k \
            -pix_fmt yuv420p -g 60 -threads 1 \
            -an -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YT_STREAM_KEY }}"
